package io.github.leedscodedojo;

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class Problem1Tests {
    @Test
    public void go() {
        Problem1 problem1 = new Problem1();

        String result = problem1.execute("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC");
        assertThat(result, is("20 12 17 21"));
    }

    @Test
    public void solver(){
        Problem1 problem1 = new Problem1();

        System.out.print(problem1.execute("CTTCACTTGGGCCATCTGGAAAACCTCAAACGACTGACTTGGGCTCCGTAATAGGTCGGATTCTTGATGCCAATGTTTTTACTCCGGCTTAGTTGCACCGCATTCTTTAGAATTAGGAGGAACGCGGGTAATACCAGGAGACCCCACCATGGTCCGAAAGTGGATTTGCCCTATAGTTGTCCATCCTTTGTACGTGTCATAGGACGTTGTAGCGTTCCAACCGTGGGCGGTCCCTCTGTTGGATGTTAGCGTTGGCGACGCCCAATCGCGATATCGCTTCACATTGGCTTACGGCTAATTGCTACACGTGTATTCGGCCCCTCAATAAACCATGTGAATAGCGCAAGTCCGCAATTAGGAAGAAACGGCGGAATATAAATACTGAGCGTCAACCACATTGTATGGGCCAGCAGCGTCACATCAATGTGTTAAGTGGTCGATTCCCCGGAGGATGGCTCACCAGGTAAGTTATGGGAGCACCGTGAGCATTTTCATTTGCAATGTTGGGATTATTCACACTGCGTTAATTTCCTTGCACTATACAATACTAAACTAATGAATGATAAGTGTGCGACCCGCCGCTATGTGAGGCAGCCGCATACTGGAAGTTGCGCCAACCGATGTAAAAGACGAGATGGGCCATAATGTATCAGAGGCACTCTGCATCCGCTTCTACGGGACTGGATCAACGAACCGCTCTAAAGTACCAACGATTAATTTGTGCACCCATCAGCAGTATTGTCACCCCGGCTTGATTCAGTACTCAGGCATCGTAGTTACCGCCCACGAATCGTTGTTATCTTCACTCGCCACATCGGCGCAGCCAGACTGGTAAGTGCGTCTCACCTTATGAACCGACGATCACCAGCCGGCTC"));
    }
}
