module roblem1

let solve (dataset:string) : string =
    let result = dataset.ToCharArray()
                 |> Array.countBy id
                 |> Array.sortBy (fun (ch,_) -> ch)
                 |> Array.map (fun (_,cnt) -> cnt.ToString())
    System.String.Join (" ", result)

//solve "AACAATTTCGATTTCGGCTGCATGGAAGCGGGCAGTAGTCGAGTTCCAGAGAAAAGTCAAAAAGCGGTTGCCAGTTGATACCAATCGGGCGATTGGCACGTAGGTGCGTGCCAGCGTGGCATCCTGTTCGCCGTTCTTAGACAGGCGCAGAGTTTATACGATATATGCGCCACCTCGGGTCGAGACCACTTCGTATCGGCTCCCATCTAGGCTGTCAGATCGGATCCTGCACGCCATATGGCGGGTGCCATTGTCTATGGACGATGGCTGCCTGATGCCGTCTCTCTGTTTAATCAGAAGGTGCGACGGTGGCTGGGCAACTAGTTATTCGGTAAGCACATAAGCTCACGCCCAATTAACATCAGGACACCTAAACAGATCCATATTAAGAGCCACTTAGCGTGCCTGTGTTTCAATTAATCACAAACACCAGGAACATGGGATTGCTCGCACGCGTATGTTATTCGTACAGGTCAAAACCCGTTGTCCCTGAGAGACCTCCGTCCGGGGTCAACGCGCCGTGTGCACCGCGCCATGTCAACGCATTCGTACCAATTCTTACAAATTGTCCAATAGAGAGACCGGCGAGGTGTTTGAGACCGCTGGATAAGAACCAATGCTTGCTGATTATCCTGTCAGTGGGCAGAAAAAAGCGCGCGAATCTTGGGCGAGTGCGGCGTTAGTGATGGTAGCCGATTATCAGTGTCCCCATTAGAATCACCCTCTATACTTGGGCATATTGCGCAGTGCAGGTCCAATATCCATACAAGACGGAAAGACCAACACGATCGTGTGGCTAACTGAGTGTGTTACAATTCAGCCCGGGGACACGATGAACGCCGCTGTAGAACGCCACGCGTCATGGACTTTAACCCAGCGTAATAATGCAGTCGCGTG" = "225 227 237 208"
