module Problem3

let solve (dataset:string) : string =

    dataset.ToCharArray()
    |> Array.map(function 
                 | 'A' -> 'T'
                 | 'T' -> 'A'
                 | 'C' -> 'G'
                 | 'G' -> 'C'
                 | x -> x)
    |> Array.rev
    |> System.String.Concat

solve "ACCGGTTCGTGCGAAGTCAGGATATAATAATTTCCACCAATGTCACTGCGGCCCAAATGCTACTATTCTAAAGCGGTAGGAGAAGTTCGGACCTGTATTAGGTAATAGCCCCATACCTCCACATGTGACCCTACAGGAGTGTACCTTATCCTTCAACCGGTCACCTTAGCGCCGTATAAAAGAGACCATTAAGGAGCCATTTGGGCAGAGATAGTTAGTCGGCGCCCGGGATTAGGGGAAGCCTAGACTGGGCAACTGTTGCTAAGGCTAATGAGCACGGGATAAGAGGACCTCGACCTGGACGAGAGCCAGGCGAAGGGTTATGACTAGCACTGTGGAGACCCGTCCAGCCTACACGCGGTGAGCTCCTGGGACCTCACGCCGGCCCACCGTCTCTGAAGGATCTCCAGGGGGTAATCCCTTTTCCAGAATGTAAGCTTTAAGAGCACTTAAGTGTCGACGGACAGTGACGCCAATAAATTCCCTACACCGATTACTGAGGGATCTTGTAGTACACTGTGAGCTCGTACGGGGATCTTTTCCATTAGCAATCCCGACGCACACCTGCACAGGGACGCACCCGACCGCCCTTGTCGGCAACGGAACTTGCGCGGAGAGGGCAACTGTCTATTGACCTCGAAGAATATGACTCAACTCCCTGTGTTGTTGCGACGGGTGAGGAGGAAGTAGACGAAGGAACAATCCGTCAATTCATCCCACTTCAGAAGTCGGCACGTTGATATGTAATGCTTGATGAGGACATACTGCCAGCTGTCATCACCTGCTAGACCCGGGATTTTATCGCTCGGTAGCGAATAGAGACATCCCTATAGTCTCGGATATCCCCTG" 
    = "CAGGGGATATCCGAGACTATAGGGATGTCTCTATTCGCTACCGAGCGATAAAATCCCGGGTCTAGCAGGTGATGACAGCTGGCAGTATGTCCTCATCAAGCATTACATATCAACGTGCCGACTTCTGAAGTGGGATGAATTGACGGATTGTTCCTTCGTCTACTTCCTCCTCACCCGTCGCAACAACACAGGGAGTTGAGTCATATTCTTCGAGGTCAATAGACAGTTGCCCTCTCCGCGCAAGTTCCGTTGCCGACAAGGGCGGTCGGGTGCGTCCCTGTGCAGGTGTGCGTCGGGATTGCTAATGGAAAAGATCCCCGTACGAGCTCACAGTGTACTACAAGATCCCTCAGTAATCGGTGTAGGGAATTTATTGGCGTCACTGTCCGTCGACACTTAAGTGCTCTTAAAGCTTACATTCTGGAAAAGGGATTACCCCCTGGAGATCCTTCAGAGACGGTGGGCCGGCGTGAGGTCCCAGGAGCTCACCGCGTGTAGGCTGGACGGGTCTCCACAGTGCTAGTCATAACCCTTCGCCTGGCTCTCGTCCAGGTCGAGGTCCTCTTATCCCGTGCTCATTAGCCTTAGCAACAGTTGCCCAGTCTAGGCTTCCCCTAATCCCGGGCGCCGACTAACTATCTCTGCCCAAATGGCTCCTTAATGGTCTCTTTTATACGGCGCTAAGGTGACCGGTTGAAGGATAAGGTACACTCCTGTAGGGTCACATGTGGAGGTATGGGGCTATTACCTAATACAGGTCCGAACTTCTCCTACCGCTTTAGAATAGTAGCATTTGGGCCGCAGTGACATTGGTGGAAATTATTATATCCTGACTTCGCACGAACCGGT"